# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 436ed59b51c25a1b8ab0d2d225fbcedfb98d16cadbba2b339b9a42b85958680cae8951f21f51c03b917adbbee8f427fb4360ed04437ef3dfade99ef708835d83

test:
  secret_key_base: 84f9a3d8520e0c80fa92c33b678b2ecdb2800e0617d26593121157069a288b63d07e40ddcbadf1c97a0285c5a2acdad857919787e5a67c392c81aec9debaabd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
